### ISSUE TITLE
Heroku error

### ISSUE THREAD

**Issue by prasoon-sipl** [GetStream/Stream-Example-PHP#11]
Post deploy exit code was not 0

[32mMigration table created successfully.[39m
[32mMigrated:[39m 2014_10_01_122413_create_users_table
[32mMigrated:[39m 2014_10_01_134126_create_items_table
[32mMigrated:[39m 2014_10_01_161014_create_pins_table
[32mMigrated:[39m 2014_10_02_100110_create_follows_table
[32mMigrated:[39m 2014_10_12_100000_create_password_resets_table
[32mMigrated:[39m 2014_10_15_121152_add_deleted_at_to_follow_table
[32mMigrated:[39m 2014_10_15_121340_add_deleted_at_to_item_table
[32mSeeded:[39m UserTableSeeder
[32mSeeded:[39m ItemTableSeeder

[37;41m                                                                               [39;49m
[37;41m  [GetStream\Stream\StreamFeedException]                                       [39;49m
[37;41m  {"code": 6, "detail": "The following feeds are not configured: 'flat'", "du  [39;49m
[37;41m  ration": "7ms", "exception": "FeedConfigException", "status_code": 400}      [39;49m
[37;41m

**Comment by tbarbugli** [comment]
thank you for reporting this, I updated the dependencies of the example and now it works again
