### ISSUE TITLE
Lumen Compatibility

### ISSUE THREAD

**Issue by tusharvikky** [GetStream/Stream-Example-PHP#9]
We cannot make this work with Lumen. Even with this https://github.com/irazasyed/larasupport.

I hope you can make it.

**Comment by tbarbugli** [comment]
what issues did you encounter during the integration with Lumen?

**Comment by hannesvdvreken** [comment]
This is a Laravel application, and Lumen is not Laravel, but a different/smaller framework with the same syntax, albeit incompatible.

So you can follow along the same steps, though some steps might need to be adapted for Lumen.

Good luck & have fun!
